name: "Integrate"

on:
  pull_request: ~
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * 1"

jobs:
  static-code-analysis:
    name: "Static Code Analysis"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
        dependencies:
          - highest
          - lowest
        include:
            - php-version: "7.4"
              codestyle: "true"
              analyse: true

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Determine composer cache directory"
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: "Install lowest dependencies from composer.json"
        if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --no-suggest --prefer-lowest

      - name: "Install highest dependencies from composer.json"
        if: matrix.dependencies == 'highest'
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Cache cache directory for vimeo/psalm"
        uses: actions/cache@v1
        with:
          path: .build/psalm
          key: php-${{ matrix.php-version }}-psalm-${{ github.sha }}
          restore-keys: php-${{ matrix.php-version }}-psalm-

      - name: "Run vimeo/psalm"
        run: vendor/bin/psalm --find-unused-psalm-suppress --shepherd --show-info=false --stats --output-format=github

  tests:
    name: "Tests"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Determine composer cache directory"
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: "Install dependencies from composer.json"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Build acceptance tests with codeception"
        run: vendor/bin/codecept build

      - name: "Run base acceptance tests with codeception"
        run: vendor/bin/codecept run
